repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: autopep8-wrapper
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: flake8
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: .*/__snapshots__/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: .*/__snapshots__/
        files: ./frontend
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        files: ./backend
