# Nombre del workflow
name: Backend Workflow

# Cuándo se ejecuta el workflow
on:
  push:
    branches: [ main ]
    paths:
      - backend/**

# Trabajos
jobs:
  # Cada uno de los jobs
  webinar-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        src: 'backend/'

  webinar-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        python-version: ['pypy-3.7', 'pypy-3.8', '3.x']
    steps:
    - uses: actions/checkout@v2
    - name: Usando Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: cd backend && pip install -r requirements.txt
    - run: cd backend && pytest

  webinar-deploy:
    needs: [webinar-testing, webinar-formatting]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://du717vx7qb.execute-api.us-east-2.amazonaws.com/github-actions-backend-tutorial
    steps:
    - uses: actions/checkout@master
    - uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-2
        function_name: github-actions-backend-tutorial
        source: backend/
