# Nombre del workflow
name: Backend Workflow

# Cuándo se ejecuta el workflow
on:
  push:
    branches: [ main ]
    paths:
      - backend/**

# Trabajos
jobs:
  # Cada uno de los jobs
  webinar-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        src: 'backend/'

  webinar-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        python-version: ['pypy-3.7', 'pypy-3.8', '3.x']
    steps:
    - uses: actions/checkout@v2
    - name: Usando Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: cd backend && pip install -r requirements.txt
    - run: cd backend && pytest

  webinar-deploy:
    needs: [webinar-testing, webinar-formatting]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://du717vx7qb.execute-api.us-east-2.amazonaws.com/github-actions-backend-tutorial
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: mariamrf/py-lambda-action@v1.0.0
      with:
        lambda_function_name: 'github-actions-backend-tutorial'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-2'
