name: Frontend Workflow

on:
  push:
    branches: [main]
    paths:
      - frontend/**

jobs:
  webinar-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check frontend/**/*.{js,ts,tsx,md}

  webinar-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: cd frontend && npm ci
      - run: cd frontend && npm test

  webinar-build:
    needs: [webinar-test, webinar-formatting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: npm install and build project
        run: |
          cd frontend && npm ci && npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: webinar-static-build
          path: frontend/build/

  webinar-deploy:
    needs: webinar-build
    environment:
      name: production
      url: http://github-actions-frontend-tutorial.s3-website-us-east-1.amazonaws.com
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/download-artifact@v2
        with:
          name: webinar-static-build
          path: build/
      - name: Deploy to AWS S3
        run: |
          aws s3 cp build/ s3://github-actions-frontend-tutorial --recursive
